code_to_question = {
    "Date": "Date",
    "Sexe": "Sexe",
    "Age": "Tranche d'âge",
    "Rura": "Zone (Rural/Urbain)",
    "Card": "Zone Géographique",
    "Etud": "Niveau d'étude",
    "pro": "CSP",
    "parent": "Métier Parent 1",
    "parent2": "Métier Parent 2",
    "Retraite": "Dernier métier (Retraité)",

    "Regime_B": "Régime spécifique ?",
    "végétarien": "Végétarien",
    "diabétique": "Diabétique",
    "gluten": "Sans Gluten",

    "C_leg": "Conso. Légumes",
    "C_frui": "Conso. Fruits",
    "C_fec": "Conso. Féculents",
    "C_lait": "Conso. Prod. Laitiers",
    "C_viaB": "Conso. Viande Blanche",
    "C_viaR": "Conso. Viande Rouge",
    "C_poi": "Conso. Poisson",
    "C_indu": "Conso. Prod. Industriels",
    "C_light": "Conso. Prod. Allégés",

    "Pd_Frais": "Attentif Prod. Frais ?",
    "Crit_influe_C": "Critère de choix principal",
    "Choix": "Critère arbitrage (ex: 2 produits)",
    "Etiqt": "Lecture Étiquette : Quoi ?",
    "Pub": "Achat influencé par Pub ?",

    "5fj": "Recommandation 5 Fruits/Légumes",
    "5flj_p": "Pourquoi non respect 5F/L ?",
    "reco": "Autre reco connue ?",
    "reco_P": "Laquelle ?",

    "A_patho": "Alimentation cause pathologies ?",
    "A_sante": "Alimentation impacte santé ?",
    "Mangé_E": "C'est quoi manger équilibré ?",
    "Repas": "Description repas équilibré",

    "VF_Eq": "V/F : Équilibré = Cher",
    "VF_Su": "V/F : Sucre Roux > Blanc",
    "VF_HO": "V/F : Huile Olive Meilleure",
    "VF_Fec": "V/F : Féculents font grossir",
    "VF_soir": "V/F : Manger léger le soir",
    "VF_saut": "V/F : Sauter repas fait maigrir",
    "VF_Eq_Reg": "V/F : Équilibré = Régime",
    "VF_Eq_bon": "V/F : Équilibré = Pas bon",
    "VF_medi": "V/F : Régime Méditerranéen bénéfique",

    "pdp": "1ère action pour perdre poids ?",
    "modif": "Modofications actuelles alim. ?",
    "info": "Besoin plus d'infos ?",
    "momnt": "Moment idéal pour info alim. ?",
    "Qst": "Questions personnelles ?",
    "diét": "Pourquoi pas de diététicien ?"
}
